spring:
  datasource: #配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drug
    username: root
    password: admin123
  data: #配置redis
    redis:
      host: localhost
      port: 6379
  threads:
    virtual:
      enabled: true #启用虚拟线程
  servlet:
    multipart:
      max-file-size: 3MB #单个文件大小：默认最大为1MB
      max-request-size: 15MB  #单次请求总大小：默认最大为10MB

mybatis: #配置MyBatis
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    #开启驼峰命名映射
    cache-enabled: true    #开启二级缓存(mapper级别)

server:
  servlet:
    session:
      timeout: 60m #设置会话过期时间
  port: 8080